/******************************************************************
*    			STC-51库/STC-51 library file
*
*文件名/file    : sys_type.h
*
*功能/function  : C51库主要头文件/main head file
*
*协议/licence   : GPL开源/open GPL
*
*作者/author    : J.H.Chen
*
*时间/time      : 2015-05-28
*
*说明/other     : 请勿直接修改此文件/please do not edit this file
******************************************************************/
#ifndef __SYS_TYPE_H
#define __SYS_TYPE_H


#ifndef BOOL
#define BOOL
typedef enum{false = 0, true = 1}bool;
#endif


#ifndef NULL
#define NULL   ((void *)0)
#endif

#endif