/******************************************************************
*    			STC-51库/STC-51 library file
*
*文件名/file    : c51_inc.h
*
*功能/function  : C51库主要头文件/main head file
*
*协议/licence   : GPL开源/open GPL
*
*作者/author    : J.H.Chen
*
*时间/time      : 2015-05-28
*
*说明/other     : 请勿直接修改此文件/please do not edit this file
******************************************************************/
#ifndef __C51_INC_H
#define __C51_INC_H


//------------------------------------------------------------
//--请勿修改以下代码--please do not modify the following code-
#ifdef 		STC10Fxx
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#include  "STC10Fxx.h"
#define   UART_USE_T1
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC11F0xE
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#include  "STC11Fxx.h"
#define   UART_USE_T1
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC11FxxXE
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#include  "STC11Fxx.h"
#define   UART_USE_T1
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC12Cxx52
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#ifdef    LIB_ADC_USE
#ifndef   PROJECT_USE_AD 
#define   PROJECT_USE_AD
#endif    
#endif
#include  "STC12C20xx.h"
#define   UART_USE_T1
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC12C54xx
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#ifdef    LIB_ADC_USE
#ifndef   PROJECT_USE_AD 
#define   PROJECT_USE_AD
#endif    
#endif
#include  "STC12C54xx.h"
#define   UART_USE_T1
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC12C56xx
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#ifdef    LIB_ADC_USE
#ifndef   PROJECT_USE_AD 
#define   PROJECT_USE_AD
#endif    
#endif
#include  "STC12C56xx.h"
#define   UART_USE_T1
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif

#ifdef 		STC12C52xx
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#ifdef    LIB_ADC_USE
#ifndef   PROJECT_USE_AD 
#define   PROJECT_USE_AD
#endif    
#endif
#include  "STC12C52xx.h"
#define   UART_USE_T1
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC12C5Axx
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#ifdef    LIB_ADC_USE
#ifndef   PROJECT_USE_AD 
#define   PROJECT_USE_AD
#endif    
#endif
#include  "STC12C5Axx.h"
#define   UART_USE_T1
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC15F10xE
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#include  "STC15F10xE_20xE.h"
#define   UART_USE_T1
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC15F20xEA
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#ifdef    LIB_ADC_USE
#ifndef   PROJECT_USE_AD 
#define   PROJECT_USE_AD
#endif    
#endif
#include  "STC15F10xE_20xE.h"
#define   UART_USE_T1
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC15W4KxxS4
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#ifdef    LIB_ADC_USE
#ifndef   PROJECT_USE_AD 
#define   PROJECT_USE_AD
#endif    
#endif
#include  "STC15W4Kxx.h"
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC15W2Kxx
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#ifdef    LIB_ADC_USE
#ifndef   PROJECT_USE_AD 
#define   PROJECT_USE_AD
#endif    
#endif
#include  "STC15W2Kxx.h"
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC15F2KxxS2
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#ifdef    LIB_ADC_USE
#ifndef   PROJECT_USE_AD 
#define   PROJECT_USE_AD
#endif    
#endif
#include  "STC15F2Kxx.h" 
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC15F4xxAD
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#ifdef    LIB_ADC_USE
#ifndef   PROJECT_USE_AD 
#define   PROJECT_USE_AD
#endif    
#endif
#include  "STC15F4xxAD.h"
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC15W10x
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#include  "STC15Wxx.h"
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC15W1KxxS
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#include  "STC15Wxx.h"
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC15W1KxxPWM
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#include  "STC15Wxx.h"
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC15W1K2xS
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#include  "STC15Wxx.h"
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC15W4xxS
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#include  "STC15Wxx.h"
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif


#ifdef 		STC15W4xxAS
#ifndef 	MCU_IS_USE
#define 	MCU_IS_USE
#ifdef    LIB_ADC_USE
#ifndef   PROJECT_USE_AD 
#define   PROJECT_USE_AD
#endif    
#endif
#include  "STC15Wxx.h"
#else
#error  mcu type multi choose, please choose only one in <c51_config.h>
#endif
#endif





#ifndef  MCU_IS_USE
#error  mcu type is not choose, please choose in <c51_config.h>
#endif 


#ifdef PROJECT_USE_AD
#include "C51_ADC.H"
#endif

#ifdef LIB_EEPROM_USE
#include "C51_EEPROM.H"
#endif 

#ifdef LIB_UART_USE
#include "C51_UART.H"
#endif 

#endif