/******************************************************************
*    			STC-51库/STC-51 library file
*
*文件名/file    : C51_Lib.h
*
*功能/function  : C51库主要头文件/main head file
*
*协议/licence   : GPL开源/open GPL
*
*作者/author    : J.H.Chen
*
*时间/time      : 2015-05-28
*
*说明/other     : 请勿直接修改此文件/please do not edit this file
******************************************************************/
#ifndef __C51_LIB_H
#define __C51_LIB_H

#define  EN_TYPE_SELECT


#include "C51_conf.h"

#include "C51_GPIO.H"

#include "C51_Timer.H"

#include "stdint.h"


#define  LIB_VERSION     "v0.1.0"


#endif