/******************************************************************
*    			STC-51库/STC-51 library file
*
*文件名/file    : stdint.h
*
*功能/function  : C51库主要头文件/main head file
*
*协议/licence   : GPL开源/open GPL
*
*作者/author    : J.H.Chen
*
*时间/time      : 2015-05-28
*
*说明/other     : 请勿直接修改此文件/please do not edit this file
******************************************************************/
#ifndef __stdint_H
#define __stdint_H

typedef unsigned char  uint8;
typedef signed char    sint8;	

typedef unsigned int   uint16;
typedef signed int     sint16;

typedef unsigned long  uint32;
typedef signed long    sint32;

#endif